### ISSUE TITLE
Implement using Rust and/or Go

### ISSUE THREAD

**Issue by impredicative** [partiql/partiql-lang-kotlin#111]
Kotlin is fine for Java users, but the rest of us need a compiled Rust or Go implementation that we can just drop in on a server. Obviously we need APIs for Python, etc. too.

**Comment by raganhan** [comment]
We don't have any current plans to ​implement PartiQL in another language. However we'd be happy to help with guidance to anyone that wants to implement PartiQL following the [specification](https://github.com/partiql/partiql-spec). 

For questions that are not specific to the Kotlin reference implementation I encourage you to use either the [PartiQL community](https://community.partiql.org/) for general questions or the [specification](https://github.com/partiql/partiql-spec) repository for specification related question.
