### ISSUE TITLE
Typo (PatiQL => PartiQL)

### ISSUE THREAD

**Issue by mikelabib** [partiql/partiql-lang-kotlin#115]
"PatiQL" should be "PartiQL"

Can be found in this section:

Open Source
**PatiQL** syntax, semantics, the embeddable reference interpreter, CLI, test framework, and tests are licensed under the Apache License, version 2.0, allowing you to freely use, copy, and distribute your changes under the terms of your choice.

**Comment by dlurton** [comment]
This was fixed.  Thanks.
