### ISSUE TITLE
What about c++, .NET implementations?

### ISSUE THREAD

**Issue by win32nipuh** [partiql/partiql-lang-kotlin#119]
What about c++, .NET implementations, samples?

**Comment by raganhan** [comment]
We don't have any current plans to ​implement PartiQL in another language. However we'd be happy to help with guidance to anyone that wants to implement PartiQL following the [specification](https://github.com/partiql/partiql-spec). 

For questions that are not specific to the Kotlin reference implementation I encourage you to use either the [PartiQL community](https://community.partiql.org/) for general questions or the [specification](https://github.com/partiql/partiql-spec) repository for specification related question.

Thank you
