### ISSUE TITLE
v0.13.1 CLI hangs on invalid queries

### ISSUE THREAD

**Issue by alancai98** [partiql/partiql-lang-kotlin#1230]
## Description
Running an invalid query in the v0.13.1 CLI causes the CLI to hang. Previously, this would result in a PartiQL error.

## To Reproduce
1. Pull down v0.13.1 CLI or build `main` branch CLI
2. Run an invalid query (syntax or evaluation)
3. Query hangs unless CTRL+C is used
```
Welcome to the PartiQL shell!
Typing mode: LEGACY
Using version: 0.13.1-8a8fdd09
PartiQL> SELECT;
^C==='
'Compilation cancelled.'
---
OK!
```

## Expected Behavior
Expect the previous behavior of giving a PartiQL error without hanging.

## Additional Context
- Java version: 11
- PartiQL version: 0.13.1

**Comment by alancai98** [comment]
v0.13.0's CLI (the previous version) gives an error:
```
Welcome to the PartiQL shell!
Typing mode: LEGACY
Using version: 0.13.0-591d7aaf
PartiQL> SELECT;
Parser Error: at line 1, column 7: unexpected token found, COLON_SEMI : ';'
no viable alternative at input 'SELECT;'
ERROR!
```
These were the commits between v0.13.0 and v0.13.1: https://github.com/partiql/partiql-lang-kotlin/compare/v0.13.0-alpha...v0.13.1-alpha. Seems like https://github.com/partiql/partiql-lang-kotlin/commit/1c08148730c82aa245393a748ddec2d8ab905c46 was the only commit that affected the CLI.

**Comment by johnedquinn** [comment]
Interesting. It seems like when https://github.com/partiql/partiql-lang-kotlin/commit/1c08148730c82aa245393a748ddec2d8ab905c46 placed the compilation/execution into multiple threads, we aren't able to adequately catch exceptions. If we add that handling to the executor service, I figure it should be fixed.
