### ISSUE TITLE
Implement UNION operator

### ISSUE THREAD

**Issue by raganhan** [partiql/partiql-lang-kotlin#13]
Section 13 of the specification.

**Comment by dlurton** [comment]
https://github.com/partiql/partiql-lang-kotlin/issues/224 should really be fixed before this issue is attempted.

**Comment by RCHowell** [comment]
I will take a look into this one. Looks like the parser already supports this, but it needs to be added to the evaluator.

**Comment by RCHowell** [comment]
Before getting started on this, I/we will need to confirm the specification for UNION, INTERSECT, and EXCEPT. As of now, these are not defined in the specification, and I need to do a little bit of research as to why these were left out.

https://partiql.org/assets/PartiQL-Specification.pdf

> Finally, notice that the above discussion of SFW queries did not capture the set operators UNION, INTERSECT and
EXCEPT. As is the case with SQL semantics too, the coordination of ORDER BY with the set operators requires attention,
as discussed in Section ??.

**Comment by RCHowell** [comment]
RFC is in review https://github.com/partiql/partiql-docs/pull/7

**Comment by RCHowell** [comment]
RFC merged.

https://github.com/partiql/partiql-docs/blob/main/drafts/0007-RFC-BAG-OPERATORS.md

**Comment by RCHowell** [comment]
Closing in favor of https://github.com/partiql/partiql-lang-kotlin/issues/184
