### ISSUE TITLE
Shadow the ANTLRv4 runtime dependency to avoid conflicts.

### ISSUE THREAD

**Issue by RCHowell** [partiql/partiql-lang-kotlin#1407]
## Relevant Issue/Bug

The partiql-parser package uses the ANTLRv4 runtime (4.10.x) which conflicts with other projects that require different minor versions of this dependency. A reasonable solution is to shade (aka re-package) this dependency.

## Requested Solution/Feature

The partiql-parser repackages the antlr runtime dependency so customers who need to consume an incompatible minor version of it can consume both.

## Describe Alternatives
- jarjar
- shadow
- vend the runtime internally + ctrl+f/r generated-src (perhaps too hacky)

## Additional Context
N/A

## DoD (Definition of Done)
1. The partiql-parser library does not have an antlr runtime dependency*
2. The antlr runtime dependency is shadowed (aka move the package name to avoid conflicts)
3. The generated sources use the shaded names

**Comment by alancai98** [comment]
Closed by #1439.
