### ISSUE TITLE
PartiQL.g4 should be declared as a parser grammar

### ISSUE THREAD

**Issue by kaby76** [partiql/partiql-lang-kotlin#1472]
## Description

I maintain [grammar-g4](https://github.com/antlr/grammars-v4), the large library of Antlr4 grammars. Someone mentioned a [problem with using the PartiQL grammar with the Go target](https://github.com/antlr/antlr4/issues/4632). After looking at this grammar carefully, I highly recommend that you change the [declaration statement of PartiQL.g4](https://github.com/partiql/partiql-lang-kotlin/blob/8402db6333b805e88764c89d58764f05a3c454d7/partiql-parser/src/main/antlr/PartiQL.g4#L1) to be `parser grammar PartiQLParser;`, and rename the file PartiQLParser.g4.

The problem is that PartiQL.g4 is a **combined grammar**, but you also declare a split grammar for the lexer, [PartiQLTokens.g4](https://github.com/partiql/partiql-lang-kotlin/blob/8402db6333b805e88764c89d58764f05a3c454d7/partiql-parser/src/main/antlr/PartiQLTokens.g4). If someone adds a lexer rule, or a string literal to PartiQL.g4, a second lexer class will be generated. A parser can only reference one token stream at a time, which means it may not work as intended. Since PartiQL.g4 only contains parser rules, it should be declared as a parser grammar.

**Comment by RCHowell** [comment]
Thank you very much for this issue! This is super insightful and we appreciate the advice on maintaining better grammars.

**Comment by RCHowell** [comment]
This suggestion was merged in #1474
