### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by rhinomode** [partiql/partiql-lang-kotlin#155]
https://github.com/partiql/partiql-lang-kotlin/blob/master/cli/README.md  

The link with text = "CLI.md" links to nowhere.

**Comment by rhinomode** [comment]
https://github.com/partiql/partiql-lang-kotlin/blob/master/docs/user/CLI.md

I guess it should point here (above) instead of here (below)

https://github.com/partiql/partiql-lang-kotlin/blob/docs/user/CLI.md

**Comment by dlurton** [comment]
Fixed by #156
