### ISSUE TITLE
Add uniform error reporting (codes) across parser, planner, and evaluator

### ISSUE THREAD

**Issue by johnedquinn** [partiql/partiql-lang-kotlin#1597]
## Requested Solution/Feature
- This issue is to track the consolidation of error reporting to provide a consistent experience for end-customers.
- Due to recent requests, it may be in the best interest for the PartiQL library to standardize a small set of error codes that may be used across implementations.

## DoD (Definition of Done)
- [x] Consistent error reporting mechanism across all components of the library
- [x] Standardized error codes
- [x] Exceptions should (likely) never be thrown on the component level

**Comment by RCHowell** [comment]
Closed by #1615
