### ISSUE TITLE
`SELECT * FROM foo` and `SELECT f.* FROM foo AS f` have different results if `foo` is a collection of a lists or bags

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-lang-kotlin#169]
I'm nearly certain that each of the queries below should have an identical result, but instead the results are as shown.

In the examples provided below, I would have expected the result to match the result for `SELECT *`.  The examples with `SELECT foo.*` have what I believe to be the incorrect result.  Note that when `foo` is a list of structs, the result is as expected.  

This this is likely happening because the logic for `<expr>.*` doesn't differentiate between structs (which have the correct behavior) and the other collection types.  (To be sure, it is a good question as to whether or not it should differentiate.)

For bags:

```
PartiQL> SELECT * FROM [<<1, 2>>] as foo
   | 
===' 
<<
  {
    '_1': <<
      1,
      2
    >>
  }
>>
--- 
OK!
PartiQL> SELECT foo.* FROM [<<1, 2>>] as foo
   | ===' 
<<
  {
    '_1': 1,
    '_2': 2
  }
>>
--- 
OK!
PartiQL> 
```
For lists:
```
PartiQL> SELECT * FROM [[1, 2]] as foo
   | 
===' 
<<
  {
    '_1': [
      1,
      2
    ]
  }
>>
--- 
OK!
PartiQL> SELECT foo.* FROM [[1, 2]] as foo
   | 
===' 
<<
  {
    'null': 1,
    'null': 2
  }
>>
--- 
OK!
```

**Comment by RCHowell** [comment]
All of these queries produce the same results
```
PartiQL> SELECT * FROM [<<1, 2>>] as foo
   |
==='
<<
  {
    '_1': <<
      1,
      2
    >>
  }
>>
---
OK!
PartiQL> SELECT foo.* FROM [<<1, 2>>] as foo
   |
==='
<<
  {
    '_1': <<
      1,
      2
    >>
  }
>>
---
OK!
PartiQL> SELECT * FROM [[1, 2]] as foo
   |
==='
<<
  {
    '_1': [
      1,
      2
    ]
  }
>>
---
OK!
PartiQL> SELECT foo.* FROM [[1, 2]] as foo
   |
==='
<<
  {
    '_1': [
      1,
      2
    ]
  }
>>
---
OK!
```
