### ISSUE TITLE
Mysterious CLI Behavior

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-lang-kotlin#172]
Create a `foo.ion` file containing the text "1" and execute the following command:

```
./partiql --query="1" --input=./foo.ion
```

Where `./partiql` is a recently unzipped distribution from `cli/build/distributions` which exists after a successful build.

The command simply executes and returns zero.

I would expect that the output should contain "1" instead.

**Comment by raganhan** [comment]
Can't reproduce with current `master` but got no response with 0.1.1 
```
$ ./partiql --query="1" --input=./foo.ion
1
```

I think this was caused by the same bug that caused #206
