### ISSUE TITLE
Add Equivalent Java Examples

### ISSUE THREAD

**Issue by raganhan** [partiql/partiql-lang-kotlin#19]
Currently, the `examples` project contains usage of the public API in Kotlin.

We should also have a Java version of each of these examples to help keep us mindful of what using the public API looks like from Java.  It will also help customers to deal with any deficiencies in the API as a result of not enforcing an API that conforms to idiomatic Java.

**Comment by RCHowell** [comment]
I see we already have `examples/java` with CSVJavaExample and S3Example. What do we believe the criteria to close this old issue is? Do we wish to recreate every Kotlin example in Java?

**Comment by am357** [comment]
@RCHowell good call out. Typically we want a definition of done (DoD) for each issue we create. For this, I believe we at least need the binding and parser examples in Java—e.g.[EvaluationWithBindings.kt](https://github.com/partiql/partiql-lang-kotlin/blob/main/examples/src/kotlin/org/partiql/examples/EvaluationWithBindings.kt) and [ParserExample.kt](https://github.com/partiql/partiql-lang-kotlin/blob/main/examples/src/kotlin/org/partiql/examples/ParserExample.kt).

**Comment by RCHowell** [comment]
Great. I will get those out.
