### ISSUE TITLE
Add ability to output results to newline-separated Ion

### ISSUE THREAD

**Issue by therapon** [partiql/partiql-lang-kotlin#207]
I want to pass in an Ion file, run a select on it, and then output a list of results as a file with a record per line.

However, the current implementation puts all results on a single massive line.

**Comment by popematt** [comment]
The record delimiter is controlled by [_Private_IonTextWriterBuilder](https://github.com/amzn/ion-java/blob/master/src/com/amazon/ion/impl/_Private_IonTextWriterBuilder.java#L148-L156). While we could write the newlines directly in the CLI code, a better way to do this is to make this configurable in the IonTextWriterBuilder. I've created https://github.com/amzn/ion-java/issues/350 to expose that functionality.
