### ISSUE TITLE
Implement `COLL_` aggregate variants

### ISSUE THREAD

**Issue by therapon** [partiql/partiql-lang-kotlin#222]
Given the query:

```
select day, sum(s.readings) as readings_sum
from `[{ day: 1, readings: [1, 2, 3]}, { day: 2, readings: [4, 5, 6]}]` as s
group by day
```

We'd like to be able to get a result like this:

```
<< 
   { 'day': 1, 'readings_sum': 6 },
   { 'day': 2, 'readings_sum': 15 }
>>
```

However the above query barfs with the error:  `: Expected number: [1,2,3]` because `SUM` doesn't know how to iterate over a list when its used within the context of a select list.

**EDIT:  the below query only works when there is a single row--I am not aware of a work-around that works with multiple rows.**
The only work-around AFAIK is to use a subquery like so (note:  this won't even work until after  `GROUP BY` aggregate support is completed):  

```
select "day", sum(reading) 
from (
    select "day", r as reading 
    from `[{ day: 1, readings: [1, 2, 3]}, { day: 2, readings: [4, 5, 6]}]` as s 
        join s.readings as r
)
```

Currently, PartiQL aggregates work as SQL-92 aggregates that require scalar values when used in a select list, otherwise they work on containers.  

The minimum we would need to do is to implement the non-context aware `COLL_` variants of the aggregate functions--that way `COLL_SUM` can be used here instead of `SUM`.

We need `coll_sum` to make this work:

```
select "day", coll_sum(s.readings) as readings_sum
from `[{ day: 1, readings: [1, 2, 3]}, { day: 2, readings: [4, 5, 6]}]` as s
```

We should also consider making it an error to call one of the non-`COLL_` aggregate functions outside the context of a select list.

Relevant section of the PartiQL specification:
```
10.2.3 Designation of SQL aggregate functions
Each implementation will have a list of SQL aggregate functions, which are not necessarily just the ones prescribed by the standard (COUNT, SUM, AVG, etc). (Recall from Section 10.2.2 that SQL aggregate functions do not use an explicit group variable.)
Furthermore, it is required that for each SQL aggregate function f, if an implementation offers a corresponding core PartiQL aggregate function, the Ion SQL++ function is named COLL_f. For example, the core PartiQL aggregate COLL_AVG corresponds to the SQL aggregate AVG. Nevertheless, it is possible that an implementation offers only COLL_AVG or offers only AVG. The semantic relationship between the SQL aggregate function and the correspond-ing core PartiQL aggregate function is the one explained in Section 10.2.2: The SQL aggregate functions do not input explicit group variables and, thus, their semantics are explained by the reduction to the corresponding corePartiQL aggregate.
```

**Comment by RCHowell** [comment]
https://github.com/partiql/partiql-lang-kotlin/commit/7080a5fc13d959494b4d02719bb559655e03bdac
