### ISSUE TITLE
CLI doesn't flush the IonWriter when --query is used

### ISSUE THREAD

**Issue by zslayton** [partiql/partiql-lang-kotlin#238]
When running the `partiql` CLI in non-interactive mode (i.e. using `--query`), the result set for the provided query is calculated and [written to an `IonWriter`](https://github.com/partiql/partiql-lang-kotlin/blob/b6f82f725654d909ef7293f4208e1c4779bc200f/cli/src/org/partiql/cli/Cli.kt#L45-L49). The program then ends without `flush()`ing the `IonWriter`, often leaving some or all of the results in the buffer. For small result sets, this means the program exits without printing anything.

**Comment by zslayton** [comment]
I just noticed that Kotlin's [`use` method](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/use.html) is meant to handle calling `close()`, so now I'm unsure why the results aren't always printed.

**Comment by therapon** [comment]
Which version of partiql are you using? This might be related to https://github.com/partiql/partiql-lang-kotlin/commit/cfcd9bc46aa6d77fdf1de020097aab04ef24d9c9

**Comment by therapon** [comment]
I believe this was fixed. If the issue persists please re-open.
