### ISSUE TITLE
Use of MIN function causes unbound binding exception 

### ISSUE THREAD

**Issue by therapon** [partiql/partiql-lang-kotlin#252]
version 0.2.1

Given the following data 

```
{ 
    'products': [ 
    { 
        'title': 'The unbearable lightness of being', 
        'author': 'Milan Kundera', 
        'price' : [12, 11, 9.99]
    } , 
    { 

        'title': 'How to travel with a salmon',
        'author': 'Umberto Eco', 
        'price' : [10, 5.99]
    } , 
    { 

        'title': 'And the ass saw the angel',
        'author': 'Nick Cave', 
        'price' : [8, 5.99]
    }]
} 
```

The following query errors out 

``` 
SELECT x.title, MIN(money) as price 
FROM products AS x, x.price AS money
WHERE author like '%Milan%'; 
   | 
org.partiql.lang.eval.EvaluationException: No such binding: x
	Evaluator Error: at line 1, column 8: Binding does not exist, <UNKNOWN> : <UNKNOWN>


```

While this one succeeds  

```
PartiQL> SELECT x.title, money as price  FROM products AS x, x.price AS money WHERE author like '%Milan%'; 
   | 
===' 
<<
  {
    'title': 'The unbearable lightness of being',
    'price': 12
  },
  {
    'title': 'The unbearable lightness of being',
    'price': 11
  },
  {
    'title': 'The unbearable lightness of being',
    'price': 9.99
  }
>>
--- 


```

**Comment by dlurton** [comment]
If there's a bug here I believe it to be the that the error message is confusing.

The origin of this error makes more sense if you consider what's going on behind the scenes when any aggregate functions are being used in the select list.  The compiler is essentially treating this query as if it had an empty `GROUP BY` clause, i.e.

```
SELECT x.title, MIN(money) as price 
FROM products AS x, x.price AS money
WHERE author like '%Milan%'; 
GROUP BY /* none */
```

This means that the result of the empty `GROUP BY` clause is fed into the select projection.

To make this query work as expected, you need to include `x.title` in the `GROUP BY` clause and it should just work: `GROUP BY x.title`

**Comment by dlurton** [comment]
While writing the following, a practical way of providing the right error message became obvious:

When any grouping is enabled (expclit or implicit) and an unresolved variable is detected, check to see if the unresolved variable is one of the aliases defined in the `FROM` clause.  This sounds easy, but I think some care must be taken to ensure this logic is applied only in the right contexts, for instance, in the `HAVING` and `LIMIT` clauses as well as the select list and when grouping is enabled.

Implementation of this is I think is just a matter of prioritization.

Background:

Given a global environment:

```
{ 
    stores: << 
        { city: Seattle, sales: 100 },
        { sales: 101 }
    >>
}
```

And the query:

```
SELECT 
    SUM(s.sales) as totalSales
    s.city
FROM stores AS s
// Implicit: GROUP BY MISSING GROUP AS $g
```

The output of the implicit group by can be thought of as:

```
<<
    { $g: <<   
        { s: { city: Seattle, sales: 100 } },
        { s: { sales: 101 } }
        >>
    }
>>
```

`$g` here is a logical construct used to denote the rows from the output clause that make up a single group.  Within 
an aggregate function call's argument, variable lookup is scoped to be within `$g`.  However, for `s` in the second
select list item, variable lookup is scoped to the current row of the top level in the group by output and proceeds to 
the parent scope which would normally be either the global scope or a parent SFW query. If no variable is found, we
currently throw a normal "undefined variable" error.  We would need to change this logic to see if the undefined 
variable was defined in one of the FROM source aliases and if so, throw an error message indicating it was not
included in the `GROUP BY` clause.
