### ISSUE TITLE
Command history for the REPL

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-lang-kotlin#255]
Add the functionality of [`rlwrap`](https://linux.die.net/man/1/rlwrap) to the REPL.

**Comment by hglr24** [comment]
Please, this drives me insane :((  
Currently, I have to copy-paste queries into a text editor just to make small changes

**Comment by dlurton** [comment]
If you're on windows, you can try using WSL and install `rlwrap`...  Right now that's my best suggestion for windows users.
