### ISSUE TITLE
Using Star * for accessing nested field arrays

### ISSUE THREAD

**Issue by mustafaakin** [partiql/partiql-lang-kotlin#273]
Sorry if it's a dumb question, having read both Tutorial and the spec PDF, I cannot seem to find what is wrong with the following code while accesin a nested field:

Sample data using Kotlin custom code derived from examples:

```
  {
    "field": {
      "s1": "hello",
       "s2": "wow",
       "s3": [1,2,3],
       "s4": [{
        "name": "one",
        "value": "1"
       }], 
       "s5": [{
        "name": "one",
        "value": "1"
       },{
        "name": "two",
        "value": "2"
       }], 
     }
  }
```

Following works:

```sql
SELECT t.field.s3 FROM tbl t WHERE 1 in t.field.s3
```

These ones don't:

```
SELECT t.field.s4 FROM tbl t WHERE t.field.s4[*].name = 'one'  <- empty string
SELECT t.field.s4 FROM tbl t WHERE t.field.s4[*]['name'] = 'one'  <- empty string
```

Are my assumptions about * expansion wrong? Of course the following ones work:

```
SELECT var1 FROM tbl t, t.field.s5 as var1"
SELECT var1 FROM tbl t, t.field.s5 as var1 WHERE var1.name = 'one'
```

I'm trying to use * because it feels more intiutive to do so, but got confused and would love any pointers.

**Comment by therapon** [comment]
That is a good question. Reading up on the specification and using the PartiQL REPL I think I can offer an explanation here. 

* From the PartiQL Spec 

Using a wildcard in a path that is **not** in a `SELECT` clause is explained as a reduction (think re-write) to other PartiQL features. The relevant section is 4.3. The case used in your sample (thanks for that it was really helpful) is similar to Example 2 in the spec. Example 2 in the spec is 

```
[1,2,3][*] <=> SELECT VALUE v FROM [1,2,3] AS v 
```

Where `v` is a fresh (new and not previously used) variable. Which means that the result of the expression will be a bag containing the values 1, 2, 3, i.e., `<<1,2,3>>` using PartiQL syntax

* From your example 

The query from your example 
```
SELECT t.field.s4 
FROM   tbl t 
WHERE  t.field.s4[*].name = 'one' 
```

If we apply the rewrite from the spec will give us 

```
SELECT t.field.s4 
FROM   tbl t 
WHERE  (SELECT VALUE v FROM t.field.s4[*].name AS v) = 'one' 
```
Which will lead to using `=` on `one` and a bag that holds the results of `(SELECT VALUE v FROM t.field.s4[*].name AS v) `. This will result to `FALSE` causing the query's `WHERE` clause to filter (remove) all rows and return the empty bag `<<>>` 

Given that the PartiQL CLI allows any sub-expression and using `tbl` as the name for the sample data provided in this issue observe 

```
PartiQL>  tbl.field.s4[*]['name']
   | 
===' 
<<
  'one'
>>
--- 
OK! (1 ms)
PartiQL>  tbl.field.s4[*]['name'] = 'one'
   | 
===' 
false
--- 
OK! (1 ms)
PartiQL>  tbl.field.s4[*].name
   | 
===' 
<<
  'one'
>>
--- 
OK! (0 ms)
PartiQL>  tbl.field.s4[*].name = 'one'
   | 
===' 
false
--- 
OK! (1 ms)
PartiQL>  tbl.field.s4[*]['name']
   | 
===' 
<<
  'one'
>>
--- 
OK! (2 ms)
PartiQL>  tbl.field.s4[*]['name'] = 'one'
   | 
===' 
false
--- 
OK! (2 ms)
PartiQL> 

```
