### ISSUE TITLE
Using qualified names

### ISSUE THREAD

**Issue by rychipman** [partiql/partiql-lang-kotlin#277]
The PartiQL spec indicates that the database environment can contain qualified names. However, I haven't been able to figure out how to experiment with qualified names in the kotlin implementation. I had a few questions:

1. Is there some way that I'm not aware of to create a database environment with qualified names in the kotlin REPL?
2. Does PartiQL allow unqualified references to qualified bind names in the database environment? (e.g. referring to the bind name `mydb.foo` in the query `SELECT * FROM foo`)
3. Related to the previous item, does PartiQL have support for/a way to model the concept of "current database" and `use <db>`?

**Comment by dlurton** [comment]
> 1. Is there some way that I'm not aware of to create a database environment with qualified names in the kotlin REPL?

In your example, `mydb` would just another top-level variable that's bound to a tuple containing the individual tables of the database.  To do this with the CLI, you can put the following in `example.sql`:

```
{ 
    'mydb': { 
        'widgets': << { 'foo': 1 } >>
    },
    'yourdb': { 
        'things': << { 'bar': 1 } >>
    }
}
```

Then you can access the `widgets` and `yourdb` tables with qualified notation:

```
PartiQL> select * from mydb.widgets
   | 
===' 
<<
  {
    'foo': 1
  }
>>
--- 
OK!
PartiQL> select * from yourdb.things
   | 
===' 
<<
  {
    'bar': 1
  }
>>
--- 
```

There is perhaps one downside to this, which is there is nothing stopping the user from running a query such as `select * from mydb` which would then return all of the data in all of the tables!  If you go this route, it might be a good idea to validate that the top-level variables are never accessed without qualification.  This can be done fairly easily with our new generated visitors.  I can provide an example if you'd like.

> 2. Does PartiQL allow unqualified references to qualified bind names in the database environment? (e.g. referring to the bind name mydb.foo in the query SELECT * FROM foo)

There is no notion of a  "current" database.  I believe that in theory, you could simulate this in your `Bindings` implementation.

> 3. Related to the previous item, does PartiQL have support for/a way to model the concept of "current database" and use <db>?

Not currently.  Feature requests are welcome.
