### ISSUE TITLE
bigDecimalOf type cast error

### ISSUE THREAD

**Issue by Zhouenze** [partiql/partiql-lang-kotlin#293]
Hi there,

I've found following issue with `bigDecimalOf` code:

```
    @Test
    fun typeCastIssue() {
        val zero = BigDecimal.ZERO
        println(zero == Decimal.NEGATIVE_ZERO) // true
        bigDecimalOf(zero) // throw exception
    }
```

Seems like the [when](https://github.com/partiql/partiql-lang-kotlin/blob/master/lang/src/org/partiql/lang/util/NumberExtensions.kt#L28) condition here is an equivalence test, not asserting same object. So if `num = BigDecimal.ZERO`, then it enters this branch and fail type cast.

Could you take a look? Thanks!

**Comment by therapon** [comment]
Thanks for the test to reproduce and the pointer to the code. There is a PR out to address the issue.
