### ISSUE TITLE
SelectListItemAliasVisitorTransform does not provide aliases to sub-queries

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-lang-kotlin#321]
As demonstrated in this test case:

https://github.com/partiql/partiql-lang-kotlin/blob/65d01c827f7b28e49d2cfdcdd47cee8256d10fa9/lang/test/org/partiql/lang/eval/visitors/SelectListItemAliasVisitorTransformTests.kt#L174-L187

Note that in the expected query, the sub-queries still do not have `AS` aliases.

The correct expected AST is:

```sql
SELECT 
    (SELECT n AS n FROM p) _1,
    (SELECT q AS q FROM r) AS o
FROM foo
```

**Comment by alancai98** [comment]
Fixed by #323. Merged into master by #356.
