### ISSUE TITLE
Change the `env: Environment` argument of `ExprFunction.call` to `session: EvaluationSession`

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-lang-kotlin#337]
I don't think that we should support accessing the local variables of the current context and other interpreter state from within `ExprFunction.call(env: Environment, args: List<ExprValue>)` function because `Environment` is full of implementation details of the interpreter and that might be hard to support if we later want to change how the interpreter works in some substantive way, or say, replace the interpreter entirely.

In looking at how the `env` parameter is actually used in all the built-in `ExprFunction` implementations, it's only ever used by `utcnow` to obtain the current `EvaluationSession`.  So I think we should change the `env: Environment` argument of `ExprFunction.call` to `session: EvaluationSession`

_Originally posted by @dlurton in https://github.com/partiql/partiql-lang-kotlin/pull/335#discussion_r536457231_

**Comment by johnedquinn** [comment]
By looking at the current codebase, this seems to be resolved. Closing.
