### ISSUE TITLE
Refactor dynamic variable resolution for simplicity

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-lang-kotlin#347]
Given the query:  

```
SELECT bat FROM foo, bar
```

Give that the variable `bat` is unqualified and we do not have schema to resolve it at compile time, PartiQL's evaluator includes some additional complexity needed to resolve `bat` for every row.  (Even if in the future we do have schema, this dynamic variable resolution will still needed because of open content.)

I think we could remove some of that additional complexity with a simple rewrite to be included in `StaticTypeRewriter` (or a similar variable resolution rewriter).

My proposal is the following:

- Remove dynamic variable resolution from the evaluator.  As far as the evaluator is concerned: all variables must be introduced in the `FROM` clause or exist as globals or a evaluation-time error will be raised.
- When a unresolved variable is detected in the `StaticTypeRewriter` (or whatever variable resolver we have at the time this is implemented) then we should replace such unresolved variables with a function call that accepts a field name and a variadic list of arguments, i.e. the above SQL should be rewritten to:

```
SELECT $find_first_field('bat', foo, bar) FROM foo, bar
```

`$find_first_field` will look for the field named "bat" in `foo`, and then `bar`, which seems to be a much simpler method of achieving the same result and thus will reduce complexity of the evaluator.

**Comment by yliuuuu** [comment]
Closing this issue in favor of #705, as `$find_first_field` may not be the behavior we want.
