### ISSUE TITLE
Add general parser checks for top-level only tokens (i.e. DML and DDL ops)

### ISSUE THREAD

**Issue by alancai98** [partiql/partiql-lang-kotlin#354]
While working on adding stored procedures calls (#345), which we limited to just top-level queries, I couldn't find any existing top-level token checks. We should add parser checks to prohibit using top-level tokens outside of the top-level. Currently, the parser won't throw an exception when mixing SFW queries with DML and DDL operations. So currently, a query such as `SELECT * FROM DELETE FROM foo` would not have a parser exception.

**Comment by abhikuhikar** [comment]
#373

**Comment by abhikuhikar** [comment]
This has been addressed by the [PR](https://github.com/partiql/partiql-lang-kotlin/pull/369).
