### ISSUE TITLE
Parser accepts statement that doesn't follow type-domain grammar

### ISSUE THREAD

**Issue by Zhouenze** [partiql/partiql-lang-kotlin#363]
Hi,

I noticed that there's discrepancy between the grammar parser accepts and the grammar in [partiql.ion](https://github.com/partiql/partiql-lang-kotlin/blob/master/lang/resources/org/partiql/type-domains/partiql.ion).

```
    // In org.partiql.lang.syntax SqlParserTest.kt
    @Test
    fun reproError() {
        val parsedExprNode = parse("update test set x = set test.y = 6")  // Succeed
        println(parsedExprNode.toAstStatement())                          // Fail with IllegalStateException
    }
```

Seems like parser should throw `ParserException` in this case?

Thanks!

**Comment by dlurton** [comment]
Seems related to: https://github.com/partiql/partiql-lang-kotlin/issues/354
