### ISSUE TITLE
PartiQL should use idiomatic CSV parsing

### ISSUE THREAD

**Issue by jonathanfrenz** [partiql/partiql-lang-kotlin#366]
PartiQL's CSV parser today doesn't take into account quotation marks around fields. Typical CSV writers will write a field with a comma in it to be surrounded by quotations. This is mentioned in the PartiQL code as a TODO [here](https://github.com/partiql/partiql-lang-kotlin/blob/7c6998283c20dd20e61316755c9ed3bfcbbade2c/lang/src/org/partiql/lang/eval/io/DelimitedValues.kt#L27-L29).

[CSVReader from Apache](https://commons.apache.org/proper/commons-csv/apidocs/org/apache/commons/csv/CSVParser.html) is a great example of how to implement this easily. A one-line fix could just be replacing [this line](https://github.com/partiql/partiql-lang-kotlin/blob/7c6998283c20dd20e61316755c9ed3bfcbbade2c/lang/src/org/partiql/lang/eval/io/DelimitedValues.kt#L89) with a CSVParser.parse call.

**Comment by dlurton** [comment]
We should really utilizing an existing [RFC-4180](https://tools.ietf.org/html/rfc4180) CSV parser as a dependency in the CLI project and removing the hand-rolled one we created.

**Comment by dlurton** [comment]
Example 1: the csv file has header row.  in this case, the columns should be bound to `_n` fields where n is the field number. i..e.

This selects the first three columns of `some_file.csv` which does not contain a header row:

```
select _1, _2, _3 from read_csv('some_file.csv', `{ has_header_row: true }`)
```

Example 2: the csv file has a header row.  in this case, the columns should be bound to their names:


```
select first_name, last_name, city from read_csv('some_file_with_header_row.csv', `{ has_header_row: false }`)
```

Example 3: the user does not know if there are column names.  We should try to autodetect.  


```
select * from read_csv('some_file_with_header_row.csv', `{ has_header_row: auto }`)
-- or -- 
select * from read_csv('some_file_with_header_row.csv')  -- has_header_row defaults to auto
```

Example 4: the user would like to specify a predefined csv format:

```
select * from read_csv('some_file_with_header_row.csv', `{ format: postgres }`)
```

Possible values for `format` are a subset of those defined [here](https://commons.apache.org/proper/commons-csv/apidocs/org/apache/commons/csv/CSVFormat.html) and include, `default`, `excel`, `mysql`, `rfc4180`, `oracle`, `postgres_csv`, `postgres_text`.  The other formats not included in this list seem rather obscure.

Example 5: the user would like to create a custom format:

```
select * from read_csv('some_file_with_header_row.csv', 
    `{ record_separator: '\n', ignore_empty_lines = true, ignore_sourrounding_spaces = true }`)
```

For a complete list of all the different configuration options, see:
https://commons.apache.org/proper/commons-csv/apidocs/org/apache/commons/csv/CSVFormat.html
