### ISSUE TITLE
REPL: print missing instead of null

### ISSUE THREAD

**Issue by raganhan** [partiql/partiql-lang-kotlin#37]
When printing out MISSING values it should read as MISSING instead of null

```
ionsql> MISSING
      | 
======' 
null
------- 
Result type was MISSING
OK! (1 ms)

```

Due to the REPL also displaying the data type of the result the user can tell that the result was `MISSING`, however, `null` is a misnomer and could be confusing.

This also affects `ExprValue.toString()` for missing values

*Migrated from IONSQL-427.*

**Comment by appwiz** [comment]
This looks like it's fixed. Here's what I get running the CLI:

```
> Task :cli:run
Welcome to the PartiQL REPL!
PartiQL> OK! (0 ms)
PartiQL> MISSING
   | 
===' 
MISSING
--- 
OK! (74 ms)
PartiQL> 
```

**Comment by raganhan** [comment]
@appwiz you are correct this was fixed, thanks for noticing it
