### ISSUE TITLE
Values of DATE date literals should not be the *extended* ISO-8601 date

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-lang-kotlin#382]
[This issue assumes that the values for the year component of `DATE` values should have the same constraints as that of an Ion timestamp.]

In essence:  the Ion timestamp only allows year values between 1 and 9999 while `LocalDate` accepts years in the range of -999999999 thru +999999999, if the year is prefixed with a `+` or a `-` sign.

This is because the `LocalDate.parse` method accepts the *extended* ISO-8601 date which allows for more than 4 digit years if the year is preceded by a `+` or `-` sign.  I doubt we intended to support this, given that the Ion timestamp does not.

I recommend adding some functions for validating and parsing `DATE` values that can be used by `SqlParser` and anything else such as the `CAST` functionality and `ExprValueFactory` implementation.

The following should result in an error instead of a valid AST.

```
Welcome to the PartiQL REPL!
Using version: 0.2.7-SNAPSHOT-ce4f7a0
PartiQL> DATE '+999999-03-01'
   | !!
===' 

(
  query
  (
    date
    999999
    3
    1
  )
)
--- 
OK!
```

**Comment by abhikuhikar** [comment]
Fixed by #385
