### ISSUE TITLE
Reconsider or justify modeling of `DATE` and `TIME` literals in their own sealed class

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-lang-kotlin#388]
Below we have `DateTimeType` as a `sealed` class inheriting from `ExprNode` and `DateTimeType.Date` (and eventually `DateTimeType.Time`) inheriting from `DateTimeType`.  

It's not clear in this case why `DateTimeType` needs to exist and why date and time literals do not inherit direclty from `ExprNode`.  
`DateTimeType` either needs to include documentation that justifies its existence or it should be removed.

https://github.com/partiql/partiql-lang-kotlin/blob/ce4f7a007967a947541de1ac36d3aa544a0e95bc/lang/src/org/partiql/lang/ast/ast.kt#L970-L989

**Comment by abhikuhikar** [comment]
Removed the sealed class in #489 .
