### ISSUE TITLE
Remove `AstNode.iterator` and `AstNode.children`

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-lang-kotlin#396]
These were used by the old `AstSanityValidator` which no longer exists.

**Comment by alancai98** [comment]
`AstNode.children` seems to only be currently used in
- [ast.kt](https://github.com/partiql/partiql-lang-kotlin/blob/3b2f4ec9f9753050bd448d2c996654eb132661a3/lang/src/org/partiql/lang/ast/ast.kt)
- [AstNodeTest.kt](https://github.com/partiql/partiql-lang-kotlin/blob/3b2f4ec9f9753050bd448d2c996654eb132661a3/lang/test/org/partiql/lang/ast/AstNodeTest.kt)

`AstNode.children` seems to only be currently used in
- [AstNodeTest.kt](https://github.com/partiql/partiql-lang-kotlin/blob/3b2f4ec9f9753050bd448d2c996654eb132661a3/lang/test/org/partiql/lang/ast/AstNodeTest.kt)
- [ThreadInterruptedTests.kt](https://github.com/partiql/partiql-lang-kotlin/blob/3b2f4ec9f9753050bd448d2c996654eb132661a3/lang/test/org/partiql/lang/thread/ThreadInterruptedTests.kt#L115)

Have to also consider customer code that may rely on both of these APIs.
