### ISSUE TITLE
Build fails for `DATE '9000-02-29'`

### ISSUE THREAD

**Issue by abhikuhikar** [partiql/partiql-lang-kotlin#399]
In one of the local builds, the randomly generated `date` `9000-02-29` caused an error failing with an exception `org.partiql.lang.syntax.ParserException: Text '9000-02-29' could not be parsed: Invalid date 'February 29' as '9000' is not a leap year`
Apparently, `9000` is not a leap year indeed. 
Fix the random `DATE` string [generator](https://github.com/partiql/partiql-lang-kotlin/blob/eee99ae37bd60fd92ac6ae3d8cf0558aef61223f/lang/test/org/partiql/lang/syntax/SqlParserDateTimeTests.kt#L177) to handle such cases.

**Comment by dlurton** [comment]
Another one: https://github.com/partiql/partiql-lang-kotlin/pull/405/checks?check_run_id=2548900061

**Comment by abhikuhikar** [comment]
The fix for this was overridden  when #401 was merged.
