### ISSUE TITLE
Rename DatePart to DateTimePart at various places

### ISSUE THREAD

**Issue by abhikuhikar** [partiql/partiql-lang-kotlin#409]
Carefully rename `DatePart` to `DateTimePart` in [LexerConstants.kt](https://github.com/partiql/partiql-lang-kotlin/blob/3b1037951d8dea30d6c8494f146f63f26a7c0d5f/lang/src/org/partiql/lang/syntax/LexerConstants.kt#L22).
Make sure that all the associated usages such as variable names, comments, error messages, etc should also be renamed to `DateTimePart` as required and appropriate.

**Comment by am357** [comment]
This issue has been resolved, see the following for more details:
https://github.com/partiql/partiql-lang-kotlin/commit/73c37e2afbb4e682f013b55710ea3af586b791b1
