### ISSUE TITLE
A cleaner s-expression representation of the GROUP clause

### ISSUE THREAD

**Issue by raganhan** [partiql/partiql-lang-kotlin#41]
`README-AST-V1.md` currently defines `GROUP_CLAUSE` as:

```
GROUP_FULL ::= `group` 
GROUP_PARTIAL ::= `group_partial`
GROUP_ALL ::= `group_all`
GROUP_BY_EXP ::= EXP | `(` `as` SYMBOL EXP `)`
GROUP_KIND ::= GROUP_FULL | GROUP_PARTIAL

GROUP_CLAUSE  ::= 
    `(`  GROUP_KIND
        //NOTE:  the `by` node cannot be wrapped in a term (GROUP_BY_EXPs however *can* be wrapped in a term).
        `(` `by` GROUP_BY_EXP GROUP_BY_EXP... `)` 
        //NOTE:  the `name` node *can* be wrapped in a term
        [ `(` `name` SYMBOL `)` ] ')'
    | `(` GROUP_ALL SYMBOL `)`
```

So:

`GROUP BY exp1, exp2` -> ```(group (by (id exp1 case_insensitive) (id exp2 case_insensitive)))```
`GROUP PARTIAL BY exp1, exp2` -> ```(group_partial (by (id exp1 case_insensitive) (id exp2 case_insensitive)))```
`GROUP ALL AS g` -> `(group_all g)`

We would like to consider changing the "grammar" of the AST like so:

```
GROUP_BY_EXP ::= EXP | `(` `as` SYMBOL EXP `)`
GROUP_BY_CLAUSE  ::= 
    `(` `group_by` `full` GROUP_BY_EXP... `)`
    | `(` `group_by` `partial` GROUP_BY_EXP... `)`
    | `(` `group_by` `all` SYMBOL `)`
```

Under this "grammar", the previous examples would be represented as:

`GROUP BY exp1, exp2` -> ```(group_by full (id exp1 case_insensitive) (id exp2 case_insensitive))```
`GROUP PARTIAL BY exp1, exp2` -> ```(group_by partial (id exp1 case_insensitive) (id exp2 case_insensitive))```
`GROUP ALL AS g` -> `(group_by all g)`

This proposed "grammar" is easier to understand in part because it eliminates the ambiguity regarding the location of `term` nodes and their corresponding metas.

**Comment by dlurton** [comment]
This is no longer relevant with the advent of [PIG](https://github.com/partiql/partiql-ir-generator).
