### ISSUE TITLE
Updated public release in Maven repository

### ISSUE THREAD

**Issue by ramondeklein** [partiql/partiql-lang-kotlin#411]
The [current partiql-lang-kotlin module published in the Maven repository](https://mvnrepository.com/artifact/org.partiql/partiql-lang-kotlin) is still v0.2.6 from Februari 2021. A lot of great improvements have been made (i.e. adding ORDER BY support by the PartiQL parser), so it would be great to use an updated version that includes these improvements.

Is there any timeline that indicates when new releases are published?

**Comment by abhikuhikar** [comment]
Thank you @ramondeklein for your interest. We are planning to release a new version in coming few weeks.

**Comment by dlurton** [comment]
I am preparing a maven release starting now.

**Comment by dlurton** [comment]
Maven release of `v0.3.0` completed, available here: https://repo1.maven.org/maven2/org/partiql/partiql-lang-kotlin/0.3.0/

The search.maven.org site may take several hours to update, but it's available for use as a dependency now.  

Please let us know of any issues.  

Thanks.
