### ISSUE TITLE
Integrate ktlint into Gradle build

### ISSUE THREAD

**Issue by raganhan** [partiql/partiql-lang-kotlin#43]
In order to facilitate consistency in code formatting we should see investigate if [ktlint](https://github.com/shyiko/ktlint) can reformat our code as part of (every?) build.

This will also require re-evaluating `CODE-STYLE.md` and making changes as necessary.

**Comment by therapon** [comment]
We added `detekt` but we need to decide the rules/checks first and configure accordingly.
