### ISSUE TITLE
`GROUP BY` should exist before `ORDER BY` syntactically

### ISSUE THREAD

**Issue by lziq** [partiql/partiql-lang-kotlin#452]
query1: `SELECT * FROM <<{'a': 1}, {'a': 2}, {'a': 3}>> GROUP BY a ORDER BY a`
query2: `SELECT * FROM <<{'a': 1}, {'a': 2}, {'a': 3}>> ORDER BY a GROUP BY a`

Currently, the parser can parse query2 successfully while fail to parse query1. 
However, syntactically `GROUP BY` should exist before `ORDER BY`. 
https://www.postgresqltutorial.com/postgresql-group-by/#:~:text=GROUP%20BY%0A%09customer_id-,ORDER%20BY,-SUM%20(amount)%20DESC

This problem happens probably because in https://github.com/partiql/partiql-lang-kotlin/blob/c6e3fc651b/lang/src/org/partiql/lang/syntax/SqlParser.kt#L1981-L1990, we currently deal with `order` before `group`.

**Comment by alancai98** [comment]
Also, per the PartiQL [spec](https://partiql.org/assets/PartiQL-Specification.pdf#page=9), `ORDER BY` comes **after** `GROUP BY` syntactically.

**Comment by lziq** [comment]
This issue is fixed in https://github.com/partiql/partiql-lang-kotlin/pull/464
