### ISSUE TITLE
Unit test fail when system language is not English

### ISSUE THREAD

**Issue by Zhouenze** [partiql/partiql-lang-kotlin#457]
This issue is related to localization, not a bug, just interesting behavior.

When system language is not English, Java automatically localize timestamp parsing. For example, if system language is Chinese, it stops recognizing word "July" (instead it will recognize “七月”). This causes unit tests to fail since assertion is always written in English.

https://github.com/partiql/partiql-lang-kotlin/blob/main/lang/test/org/partiql/lang/eval/builtins/ToStringExprFunctionTest.kt#L36

**Comment by johnedquinn** [comment]
Hi @Zhouenze, I'm taking a look into this issue. Going to attempt changing my locale to Spanish, as that is the only other language I can read.

**Comment by johnedquinn** [comment]
Reproduced. To reproduce:
- Change Primary Language to Spanish
- Run `./gradlew build`

Failing tests:
- ToTimestampEvaluationTest
- ToStringEvaluationTest

I'm currently attempting to manually override the locale to be en_US for all tests. Will post an update soon.

**Comment by johnedquinn** [comment]
Ok. Looks like adding the user.language and user.country JVM flags works.

I also made sure to check that we are still able to run with the appropriate expected locale. Here's the PartiQL query I ran to check in the REPL:
```
PartiQL> to_string(`1969-07-20T20:18Z`, 'MMMM d, y');
```

Output:
```
'julio 20, 1969'
```

And another command:
```
PartiQL> to_timestamp('20 julio 1979 13:18', 'dd MMMM yyyy HH:mm');
```

output:
```
`1979-07-20T13:18-00:00`
```
