### ISSUE TITLE
Why CLI requires to enter twice?

### ISSUE THREAD

**Issue by arun-gupta** [partiql/partiql-lang-kotlin#50]
[CLI docs](https://github.com/partiql/partiql-lang-kotlin/blob/master/docs/user/CLI.md) says:

```
press enter twice to execute it
```

This is non-intuitive. Why enter is required twice?

**Comment by therapon** [comment]
Maybe something that can be addressed with #63

**Comment by alancai98** [comment]
https://github.com/partiql/partiql-lang-kotlin/pull/249 added the ability to use a semi-colon to execute the query with a single enter.
