### ISSUE TITLE
Name of the repo

### ISSUE THREAD

**Issue by arun-gupta** [partiql/partiql-lang-kotlin#51]
The repo is currently called `partiql-lang-kotlin`

Kotlin is an implementation detail and should not be included in the repo name. Here are some alternate names:

- `partiql-lang`
- `partiql-engine`
- `partiql-impl`
- `reference-implementation`
- `ri`

**Comment by therapon** [comment]
I think the repo name is no set and I believe we do not have plans to change the repo name. We might eventually break out some sub-projects (CLI for example and/or PTS). 
Closing for now. Please re-open if you think there is still an issue here that we need to address.
