### ISSUE TITLE
Remove hardcoded types from the PIG domain

### ISSUE THREAD

**Issue by alancai98** [partiql/partiql-lang-kotlin#510]
There are currently some hardcoded types added to the PIG domain. See `partiql.ion`:
https://github.com/partiql/partiql-lang-kotlin/blob/fb7992468158d947557dc979f48a5f41ce83aa43/lang/resources/org/partiql/type-domains/partiql.ion#L392-L414

These types are temporary and should be removed as soon as possible so users don't take a dependency on these types. Removal of these types may cause downstream changes to [AstDeserialization.kt](https://github.com/partiql/partiql-lang-kotlin/blob/fb7992468158d947557dc979f48a5f41ce83aa43/lang/src/org/partiql/lang/ast/AstDeserialization.kt#L164-L166), [CustomTypeVisitorTransform.kt](https://github.com/partiql/partiql-lang-kotlin/blob/fb7992468158d947557dc979f48a5f41ce83aa43/lang/src/org/partiql/lang/eval/visitors/CustomTypeVisitorTransform.kt#L10), [StatementToExprNode](https://github.com/partiql/partiql-lang-kotlin/blob/fb7992468158d947557dc979f48a5f41ce83aa43/lang/src/org/partiql/lang/ast/StatementToExprNode.kt#L351-L368), [ExprValueType.kt](https://github.com/partiql/partiql-lang-kotlin/blob/fb7992468158d947557dc979f48a5f41ce83aa43/lang/src/org/partiql/lang/eval/ExprValueType.kt#L218), and [SqlParserCustomTypeCatalogTests.kt](https://github.com/partiql/partiql-lang-kotlin/blob/fb7992468158d947557dc979f48a5f41ce83aa43/lang/test/org/partiql/lang/syntax/SqlParserCustomTypeCatalogTests.kt#L15-L18).

There is no support for these types, beyond parsing and (de)serialization, and we are not aware of currently-active users. The effect of these nodes can be achieved with the generic `(custom_type ...)` node.

**Comment by lziq** [comment]
See https://github.com/partiql/partiql-lang-kotlin/pull/755#discussion_r967346752 for the reason to remove.
