### ISSUE TITLE
Fix (de)serialization of StaticType in StaticTypeMeta

### ISSUE THREAD

**Issue by alancai98** [partiql/partiql-lang-kotlin#512]
Current (de)serialization of `StaticTypeMeta` based on ISL mappers does not work as expected and the implementation is incomplete. We should either implement the (de)serialization code or delete the incomplete implementation since there are no uses currently.

If (de)serialization of `StaticType` is to be fixed in `StaticTypeMeta`, apply fix here:
https://github.com/partiql/partiql-lang-kotlin/blob/fb7992468158d947557dc979f48a5f41ce83aa43/lang/src/org/partiql/lang/ast/StaticTypeMeta.kt#L21-L22

**Comment by johnedquinn** [comment]
Since this was deleted, closing.
