### ISSUE TITLE
Migrate fully to JUnit 5

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-lang-kotlin#577]
- There are many tests still using JUnit 4.
- There are now many test classes which mix JUnit 5's annotations and JUnit 4's assertions, which is messy.
- JUnit 4 tests don't seem to be running parallel under JUnit 5's backward compatibility runner.

One challenge:  we make somewhat heavy use of `junitparams`, which is tied to JUnit 4 and isn't needed any longer (since JUnit5 has such parameterization built in), so some non-trivial amount of mechanical refactoring will be required.  

This task will be completed when all references to JUnit 4 (and `junitparams`) are removed from the code in this repository.

Also, consider if #576 is required prior to starting this issue.  Should all tests should `import` their `assert*` functions instead of inheriting them from `TestBase`.

**Comment by RCHowell** [comment]
Closing as duplicate https://github.com/partiql/partiql-lang-kotlin/issues/205
