### ISSUE TITLE
Implement `CEIL` and `FLOOR` functions

### ISSUE THREAD

**Issue by alancai98** [partiql/partiql-lang-kotlin#602]
Similar to #601, would be good to support `CEIL` and `FLOOR` functions for decimal types. [PostgreSQL](https://www.postgresql.org/docs/current/functions-math.html)'s syntax and semantics seem a reasonable starting point for these functions.

`CEIL`/`CEILING`:
> ceil ( numeric ) → numeric ceil ( double precision ) → double precisionNearest integer greater than or equal to argumentceil(42.2) → 43ceil(-42.8) → -42
--
ceiling ( numeric ) → numeric ceiling ( double precision ) → double precisionNearest integer greater than or equal to argument (same as ceil)ceiling(95.3) → 96

`FLOOR`:
> floor ( numeric ) → numeric
floor ( double precision ) → double precision
    Nearest integer less than or equal to argument
    floor(42.8) → 42
    floor(-42.8) → -43

**Comment by RCHowell** [comment]
I will take this as a first issue to familiarize myself with the PR process.

**Comment by RCHowell** [comment]
https://github.com/partiql/partiql-lang-kotlin/pull/613
