### ISSUE TITLE
How to interact with AWS resources with REPL

### ISSUE THREAD

**Issue by quiver** [partiql/partiql-lang-kotlin#631]
Some AWS services(DynamoDB, etc.) support PartiQL natively.
Now how can I interact with these services from this REPL?

[Tutorial](https://partiql.org/tutorial.html) does not mention how to specify external data sources at all.

Is this repository intended for general purpose Particle implementation and do I have to write an AWS integration wrapper on top of this?

Best regards.

**Comment by am357** [comment]
@quiver currently PartiQL does not expose any API to enable evaluation on external sources with data at rest. Considering this, a common approach as of today is to use our current APIs to retrieve an AST from the parsed query and evaluate further by walking through and transforming the AST through rewrites. We have some [examples](https://github.com/partiql/partiql-lang-kotlin/tree/main/examples/src/kotlin/org/partiql/examples) that can help clarifying this further. For example, see the following:
- [ParserExample.kt](https://github.com/partiql/partiql-lang-kotlin/blob/main/examples/src/kotlin/org/partiql/examples/ParserExample.kt)

Please let us know if you need further assistance and we can take it from there.

**Comment by am357** [comment]
No worries @quiver. Thanks for raising this because this issue has struck @johnedquinn by an idea to provide a helper CLI helper function for DynamoDB queries; he'll update this issue with more details.

**Comment by johnedquinn** [comment]
Hi @quiver, I really liked your idea about interacting with AWS resources from the CLI. It would be greatly beneficial to be able to send PartiQL queries to services and perhaps perform additional local computation on the result.

We are thinking of creating an `extensions` library that will hold functions used by the CLI (among other things).  If you'd like to do something similar with an external service for your own work, it's as simple as extending the `BaseFunction` abstract class. `QueryDDB` is such an example (in the PR). Hope this helps.

Here's my draft PR: #635

**Comment by quiver** [comment]
@johnedquinn 

> to provide a helper CLI helper function for DynamoDB queries

Actually, I was using [stevearc/dql](https://github.com/stevearc/dql) to access DynamoDB with SQL. It should be a lot easier with PartiQL, but no one seemed to develop apps that way.

I'll try your feature this weekend.

Cheers

**Comment by quiver** [comment]
Hi, @johnedquinn

This is exactly what I wanted.

I wrote about it on my company's tech blog(in Japanese).

https://dev.classmethod.jp/articles/query-dynamodb-from-partiql-repl/

Thank you for your work.

**Comment by johnedquinn** [comment]
I took a look at DQL and your blog post. We can definitely learn from some features of DQL. Also, I'm glad this new feature was helpful to you. It's about time we implemented something like this.

I'll be sharing your post with the rest of the team. Thanks!
