### ISSUE TITLE
Determine Whether `Numeric` Type Is Modeled Correctly in PartiQL

### ISSUE THREAD

**Issue by lziq** [partiql/partiql-lang-kotlin#672]
PartiQL currently has inconsistent use of `Numeric` type. In [partiql.ion](https://github.com/partiql/partiql-lang-kotlin/blob/main/lang/resources/org/partiql/type-domains/partiql.ion#L487), it is modeled to be the same as `Decimal` type. In [StaticType](https://github.com/partiql/partiql-lang-kotlin/blob/main/lang/src/org/partiql/lang/types/StaticType.kt#L57), it is modeled as a union of all the number types. We need to decide what is the current semantics of `Numeric` type in PartiQL. Note that in most other sql languages, `Numeric` type functions the same as `Decimal` as shown [here](https://learnsql.com/blog/numeric-decimal-data-types-sql/#:~:text=There%20is%20one%20notable%20difference,numbers%20than%20the%20stated%20precision).

**Comment by yliuuuu** [comment]
The idea of a "union of types" seemingly was inspired originally from #551, where we added to a convenience enum type `TEXT` to model union of `STRING` and `SYMBOL`.

The confusion largely comes from the naming "numeric", which is commonly refers to "Exact Number Value". 

The usage of `NUMERIC` is limited to math function signature, meaning it should be an internal matter. 

The issue can be solved by renaming `NUMERIC` to something else, perhaps `NUMBER`?

**Comment by RCHowell** [comment]
See my note in #866 but essentially it's not worth modify StaticType if it will be replaced by OTS
