### ISSUE TITLE
Remove + delete `ExprNode`

### ISSUE THREAD

**Issue by alancai98** [partiql/partiql-lang-kotlin#682]
`ExprNode` has been deprecated since [v0.6.0](https://github.com/partiql/partiql-lang-kotlin/releases/tag/v0.6.0-alpha). The parser, evaluator, and AST rewriting have migrated to use PIG-generated `PartiqlAst`. By the v1.0.0 release of `partiql-lang-kotlin`, we should remove and delete `ExprNode` and its related files (e.g. [ast.kt](https://github.com/partiql/partiql-lang-kotlin/blob/ff041b28c6db53853c3b370690246bc01913a400/lang/src/org/partiql/lang/ast/ast.kt)).

**Comment by yliuuuu** [comment]
Using this comment to track the progress on removing the ExprNode in our codebase: 
Step one: Removal of V0 ast ( Meta related changes are excluded in this step). PR #863. 
Step two: Meta related clean up, focusing on removal of the deprecated `MetaContainer`. PR #869

**Comment by yliuuuu** [comment]
Step Three: Remove rewriter, ast walker/ visitor. 
Step Four: Remove the dependencies on ExprNode in our code base.
Issues left to address: issue #878 , issue #879
