### ISSUE TITLE
Request to support `INSERT` DML with `ON CONFLICT DO REPLACE EXCLUDED` clause

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-lang-kotlin#704]
My team could really use support for the `ON CONFLICT DO REPLACE EXCLUDED` clause from the [INSERT, UPSERT, and REPLACE](https://github.com/partiql/partiql-docs/pull/11/files) RFC PR.  At the moment we wish to support "put semantics", that is, if a record already exists with the specified primary key then the entire record is replaced, otherwise a new record is inserted.

As of today, the parser has only limited support for the `ON CONFLICT` clause which does not include `DO REPLACE EXCLUDED`, and then only when `INSERT INTO ... VALUE` used (which is not even part of that RFC).

Examples:

```
INSERT into foo <<{'id': 1, 'name':'bob'}>> 
ON CONFLICT DO REPLACE EXCLUDED
```

```
INSERT into foo SELECT bar.id, bar.name  FROM bar
ON CONFLICT DO REPLACE EXCLUDED
```

Success criteria:

- Parser can parse the examples above.
- Modification of any planner APIs related to DML so that the embedding application can check if `ON CONFLICT DO REPLACE EXCLUDED` was specified or not. (i.e. `DmlCommand`).

Note that my team does not require any other syntax proposed in the RFC not shown above.

**Comment by am357** [comment]
@dlurton mind clarifying further _It is modeled effectively in the AST_? do you expect a specific characteristic?

**Comment by dlurton** [comment]
I'll just take that out--it doesn't really matter how it is modeled as long as the caller can identify if the clause was included or not without a major amount of effort.
