### ISSUE TITLE
Allowing multiple MATCHES

### ISSUE THREAD

**Issue by johnedquinn** [partiql/partiql-lang-kotlin#709]
## Description

SqlParser should not allow the following query:

```
PartiQL> SELECT p FROM g2 MATCH (c) -> (d), (e) -> (f)
!!
```

## More Information

There should be a parenthesis around multiple matches: AKA: `((c) -> (d), (e) -> (f))`

I've fixed this in PartiQLParser (experimental in branch `antler`)

**Comment by vgapeyev** [comment]
@johnedquinn, I'd think this working as described with the ANTLR parser is sufficient for closing this issue? (Assign yourself first? ;-)

**Comment by johnedquinn** [comment]
Thanks !

**Comment by johnedquinn** [comment]
Resolved by #711
