### ISSUE TITLE
Trim Function only accepts lowercase `both | leading | trailing`

### ISSUE THREAD

**Issue by yliuuuu** [partiql/partiql-lang-kotlin#744]
Currently our trim function signature looks like `TRIM: [ String ] String -> String`

This implies that we are treating the optional first argument `LEADING|TRAILING|BOTH` as string instead of keywords, causing the case sensitivity issue. 

A quick work around will be adding upper case string to our Enum Class. 

https://github.com/partiql/partiql-lang-kotlin/blob/40e957a783f1726c01b512c255fe2943d1c24d06/lang/src/org/partiql/lang/eval/builtins/TrimExprFunction.kt#L161-L170

**Comment by johnedquinn** [comment]
@yliuuuu should this be closed?

**Comment by yliuuuu** [comment]
Closed by [PR#754](https://github.com/partiql/partiql-lang-kotlin/pull/754)
