### ISSUE TITLE
Fuzz testing Github workflow

### ISSUE THREAD

**Issue by RCHowell** [partiql/partiql-lang-kotlin#787]
## Relevant Issue/Bug

We have identified randomized/fuzz testing in our unit tests which we would prefer to move to a github workflow due. The thinking is, if a fuzz test catches something during the build, we don't want to disambiguate if the build failed due to functional changes or a random chance. We see value in the randomized testing, but prefer to separate randomized testing from the build's deterministic unit testing.

https://github.com/partiql/partiql-lang-kotlin/pull/779

## Requested Solution/Feature
Some tests have

## Describe Alternatives
..

## Additional Context
..

## DoD (Definition of Done)
- Randomized testing has been removed from the unit tests
- Randomized testing is run as part of Github workflow

**Comment by yliuuuu** [comment]
PR #882
