### ISSUE TITLE
New Release Date?

### ISSUE THREAD

**Issue by mustafaakin** [partiql/partiql-lang-kotlin#795]
When a new release would be done? The latest one was 0.7.0 and was on Jun 23, 2022. We'd like to incorporate some new features in our application (like https://github.com/partiql/partiql-lang-kotlin/pull/740 and many others like the formatter), but not sure whether there are breaking changes that'd need attention.

**Comment by alancai98** [comment]
Hi @mustafaakin sorry for the delay. We can't yet give a concrete data for when the next release will be done. We are still planning what else will be included in the next release and will share that outline with you once it's finalized.

The [CHANGELOG](https://github.com/partiql/partiql-lang-kotlin/blob/main/CHANGELOG.md#unreleased)'s "Unreleased" section shows all the current changes expected in the next release. So far, we've only identified: "Replaces `union`, `intersect`, `except` IR nodes with common `bag_op` IR node" (#687) as the only breaking change thus far.

Also it's worth noting some of the new APIs that are now deprecated (see [Deprecated section](https://github.com/partiql/partiql-lang-kotlin/blob/main/CHANGELOG.md#deprecated)):
- Deprecates `SqlLexer` and `SqlParser` to be replaced with the `PartiQLParserBuilder`.
- Deprecates helper method, `blacklist`, within `org.partiql.lang.eval` and introduced a functionally equivalent
  `org.partiql.lang.eval.denyList` method.
- Deprecates `TypedOpParameter.LEGACY` to be replaced with `TypedOpParameter.HONOR_PARAMETERS`

**Comment by alancai98** [comment]
To followup, we're tracking the changes that will be part of the next release, v0.8.0, in this [project board](https://github.com/orgs/partiql/projects/6/views/1). There are still a few changes we would like to merge into `main` before going through with the release:
- https://github.com/partiql/partiql-lang-kotlin/pull/797
- https://github.com/partiql/partiql-lang-kotlin/issues/794
- https://github.com/partiql/partiql-lang-kotlin/pull/831

**Comment by RCHowell** [comment]
Hi Mustafa,

As you are probably aware by this point, version 0.8.0 has been released. https://github.com/partiql/partiql-lang-kotlin/releases/tag/v0.8.0-alpha

If there are any additional concerns, please feel free to re-open
