### ISSUE TITLE
Refactor visitor & rewriters

### ISSUE THREAD

**Issue by raganhan** [partiql/partiql-lang-kotlin#8]
Our current visitor/rewriter implementation is rather non standard and lacks the ability to transform from an `ExprNode` AST to another that does not use `ExprNode` as a base class.  To remedy this, I propose the following changes:

- Rename `AstVisitor` -> `AstListener`
  - Add one method for every node type to `AstListener` (instead of just the base types like we have currently)
  - Update `AstWalker` to dispatch to these additional methods
- Rename `AstRewriter` -> `AstVistor`
  - Rename the `rewrite*` methods to `visit*`
  - Add generic argument, making it `AstVisitor<T>` and make `T` the return type of every `visit*` method.
  - Note: Do not rename `AstRewriterBase`, but do make it implement `AstVisitor<ExprNode>`

After this change, we will be using the terms `visitor`, `listener` and `walker` in the same way that `ANTLR4` does.

**Comment by dlurton** [comment]
PIG-generated visitors have taken the visitor/rewriter implementation in a different direction, this issues no longer relevant.
