### ISSUE TITLE
Add collection aggregate functions

### ISSUE THREAD

**Issue by johnedquinn** [partiql/partiql-lang-kotlin#837]
## Relevant Issue/Bug
- Somewhat relevant to #821

## Requested Solution/Feature
- We are initializing the `aggregate` relalg operator in the above linked PR
- However, in PartiQL Eval Compiler, we also support using `aggregate` functions on collections of scalars.
- We also mention its use within the specification -- search 'COLL_AVG'
- So, we should add support for `COLL_{AGG}` and also rewrite any `{AGG}` that actually is performing an aggregation on a collection of scalars.

## Describe Alternatives
- A clear and concise description of any alternative solutions or features you've considered.

## Additional Context
- I actually have a version of this working locally, but as we're waiting for #821 to be merged, I'm creating this issue to keep track.
- My local changes can correctly evaluate the following query:
  - Code:
    ```
    PartiQL> SELECT g, SUM(b) AS sum_b, COLL_SUM('all', a) AS coll_sum_a, COLL_AVG('all', a) AS coll_avg_a
       |   FROM << {'a': [0, 1], 'b': 3}, {'a': [10, 11], 'b': 4} >> AS t
       |   WHERE AVG(a) > 0.3
       |   GROUP BY a GROUP AS g
       |   ORDER BY SUM(b) DESC
    ```
  - Analysis:
    - All `COLL_SUM`'s in projection list are an explicit call to aggregate what `a` currently is at that moment (not an actual aggregation) -- AKA `a` is a list for both tuples.
    - The `SUM` in the projection list is an aggregation function. Needs to act on `b` which is a scalar binding.
    - The `AVG` in the `WHERE` clauses gets internally converted into a `COLL_AVG`
    - The `SUM` in the `ORDER BY` clause is an aggregate `SUM`

## DoD (Definition of Done)
- Something similar to the above additional context

**Comment by RCHowell** [comment]
Now that aggregations are merged, can we revisit this?
