### ISSUE TITLE
Please make these PartiQLCompilerPipeline functions public

### ISSUE THREAD

**Issue by dlurton** [partiql/partiql-lang-kotlin#947]
## Requested Solution/Feature

You've recently replaced `PlannerPipeline` with `PartiQLCompilerBuilder` (https://github.com/partiql/partiql-lang-kotlin/pull/907) but left several key functions marked as `internal`, preventing their outside of this library.  Please mark these functions as public.

For the moment, the functions of `PartiQLCompilerBuilder` we need to be public are:

- `customOperatorFactories` (this is most critical)
- `customFunctions`
- `customProcedures`

## Describe Alternatives

There are none, AFAIK.

## DoD (Definition of Done)

- Customers can invoke the above-mentioned functions.

**Comment by RCHowell** [comment]
I will leave this open until the patch release

**Comment by hpolloni** [comment]
hi, when is the next patch release?

**Comment by am357** [comment]
@hpolloni we've started the release today and published the artifact to [Maven Central](https://search.maven.org/search?q=partiql) now; once the version appears in Maven Central, we'll proceed w/ finalizing the release. It can take up to 24hrs for the new version to show up on Maven Central but usually is takes couple hours.

**Comment by am357** [comment]
The release is now completed. Please feel free to re-open the issue if needed.
