### ISSUE TITLE
Permissive mode flag (and likely some other flags) not being set in CLI/REPL

### ISSUE THREAD

**Issue by alancai98** [partiql/partiql-lang-kotlin#957]
## Description
Running the CLI/REPL and trying to set the `--typing-mode` to `PERMISSIVE` doesn't change the `CompileOption`. The other `CompileOption`-related flags like `--projection-iter-behavior`, `--typed-op-behavior`, `--undefined-variable-behavior`, `--pipeline` may also have the same issue.

## To Reproduce
1. Pulled in latest version of `partiql-lang-kotlin`'s `main` branch
2. Tried to run the REPL with `PERMISSIVE` typing mode
```shell
./partiql-app/partiql-cli/partiql.sh --typing-mode=PERMISSIVE
```
3. Received following output (typing mode should say PERMISSIVE and output of query should be `MISSING` not `NULL`)
```
... Build logic ...
Welcome to the PartiQL shell!
Typing mode: LEGACY
Using version: 0.9.1-SNAPSHOT-8ea3931b
PartiQL> UPPER(MISSING);
==='
NULL
---
OK!
PartiQL>
```

## Expected Behavior
- CLI/REPL should run the query in `PERMISSIVE` mode when the `PERMISSIVE` typing mode flag is specified

## Additional Context
- Java version: 11
- PartiQL version: 0.9.1-SNAPSHOT
- [Permissive typing mode section of the command line tutorial](https://github.com/partiql/partiql-lang-kotlin/blob/bde2a3f266b860ba71bf4e5d7137561b54fed407/docs/tutorials/Command%20Line%20Tutorial.md#permissive-typing-mode) should also be updated

**Comment by alancai98** [comment]
I looked into the bug a bit, but I’m not familiar with picocli. It likely has something to do with how the options are set in [PipelineOptions.kt](https://github.com/partiql/partiql-lang-kotlin/blob/bde2a3f266b860ba71bf4e5d7137561b54fed407/partiql-app/partiql-cli/src/main/kotlin/org/partiql/cli/pico/PipelineOptions.kt)

**Comment by RCHowell** [comment]
Fixed by https://github.com/partiql/partiql-lang-kotlin/pull/954
