### ISSUE TITLE
PartiQL compiler pipeline doble evaluation

### ISSUE THREAD

**Issue by hpolloni** [partiql/partiql-lang-kotlin#966]
## Description
The new PartiQL pipeline (planner, compiler, etc.) evaluates the plan twice: once when calling `statement.eval()` and another time when materializing the ExprValue. This is unexpected as execution of the plan should only happen once (during `statement.eval()`). 

## To Reproduce
1. Pull commit https://github.com/hpolloni/partiql-lang-kotlin/commit/030b355ecfc61b681aa188d5e0b8fbfde9d6ab26
2. Run the test.

## Expected Behavior
- Evaluation should happen once during `statement.eval()`

**Comment by RCHowell** [comment]
Hey Herman, this is an interesting issue and we've had some previous troubles with materialization to IonValues. Just taking a quick look, and trying to understand how this is happening.

The values are never actually materialized when `eval()` is called as you would expect. Instead, you will get a BagExprValue which holds a yet-to-be-instantiated sequence — where the sequence is what `eval()` creates.

The bug appears in compiling bindings to values, [the sequence is peeked to determine if a BagExprValue or ListExprValue should be created](https://github.com/partiql/partiql-lang-kotlin/blob/main/lang/src/main/kotlin/org/partiql/lang/eval/physical/PhysicalPlanCompilerImpl.kt#L289). This instantiates the sequence and is what's causing `exhausted` to be set to `true`.

This change prevents the sequence from being instantiated prematurely.
```kotlin
        return thunkFactory.thunkEnv(expr.metas) { env ->
            // var relationType: RelationType? = null
            // we create a snapshot for currentRegister to use during the evaluation
            // this is to avoid issue when iterator planner result
            val currentRegister = env.registers.clone()
            val elements = sequence {
                env.load(currentRegister)
                val relItr = bexprThunk(env)
                // relationType = relItr.relType
                while (relItr.nextRow()) {
                    yield(mapThunk(env))
                }
            }

            // Trick the compiler here to always initialize `relationType`
            ExprValue.newBag(elements)
            // when (elements.firstOrNull()) {
            //     null -> createOutputSequence(relationType, emptySequence())
            //     else -> createOutputSequence(relationType, elements)
            // }
        }
```

John originally used a meta to indicate whether or not to instantiate a bag or list which would prevent having to peek. We will make this change asap

**Comment by hpolloni** [comment]
ah! thanks. That makes sense to me as well.
